#!/bin/sh

if [ -f /etc/os-release ]
then
        . /etc/os-release
fi

if [ "$1" = "purge" ] || [ "$ID" = "rhel" ]
then
	if [ -d /var/lib/lacework ]
	then
		echo "Purging /var/lib/lacework"
		rm -rf /var/lib/lacework
	fi
	if [ -d /var/log/lacework ]
	then
		echo "Purging /var/log/lacework"
		rm -rf /var/log/lacework
	fi
fi
