#!/bin/sh

echo "Lacework package op $1"
if [ -d /run/systemd/system ]
then
	if [ "$1" = "1" -o "$1" = "upgrade" ]
	then
		systemctl restart datacollector                              || :
	else
		systemctl stop datacollector                                 || :
		systemctl --no-reload disable datacollector                  || :
	fi
elif [ -f /sbin/initctl ]
then
	initctl stop datacollector                                   || :
elif [ -f /sbin/rc-service ]
then
	rc-service datacollector stop                                || :
	rc-update del datacollector                                  || :
else
	service datacollector stop                                   || :

	status=`which chkconfig`
	if [ "$?" = "0" ];
	then
		chkconfig datacollector off                          || :
	fi

	status=`which update-rc.d`
	if [ "$?" = "0" ];
	then
		update-rc.d -f datacollector remove                  || :
	fi
fi
